@echo off
:a
echo %random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%
color 19
color f5
color c7
color 06
color 1a
color 2b
color bf
color 83
color e6
color 08
color f5
color cd
color a7
color 5f
color ac
color b9
goto a